# Generated by Django 5.1.1 on 2024-09-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_alter_userprofile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileView',
        ),
    ]
