# Generated by Django 5.1.1 on 2024-09-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_delete_userprofileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(default='cerulean', max_length=50),
        ),
    ]
