# Generated by Django 5.1.1 on 2024-09-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0007_alter_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='medicine',
            field=models.TextField(default=''),
        ),
    ]
